print("Caixa:")
print("**********")
print("*        *")
print("*        *")
print("*        *")
print("**********") 
print()
print()

print("Oval:")
print("   ****   ")
print(" *      * ")
print("*        *")
print("*        *")
print("*        *")
print(" *      * ")
print("   ****   ") 
print()
print()

print ("Seta:")
print("    *    ")
print("   ***   ")
print("  *****  ")
print("    *    ")
print("    *    ")
print("    *    ")
print("    *    ")
print()
print()

print ("losango:")
print("    *    ")
print("   ***   ")
print("  *****  ")
print(" ******* ")
print(" ******* ")
print("  *****  ")
print("   ***   ")
print("    *    ")
